platzigram/platzigram/urls.py
"""Platzigram URLs module."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),

    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='create'
    ),
    path(
        route='posts/<int:pk>/',
        view = views.PostDetailView.as_view(),
        name='detail'
    )
]

platzigram/users/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from users import views


urlpatterns = [

   

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),
     # Posts
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    )

]

platzigram/users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

platzigram/users/forms.py
"""users forms"""

#django
from django import forms
from django.contrib.auth.models import User
from users.models import Profile

class SignUpForm(forms.Form):
    """sign up form"""
    username= forms.CharField(min_length=4,max_length=50)
    password = forms.CharField(max_length=70,widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70,widget=forms.PasswordInput())
    
    first_name = forms.CharField(min_length=2,max_length=50)
    last_name = forms.CharField(min_length=2,max_length=50)
    
    email = forms.CharField(min_length=6,max_length=70,widget=forms.EmailInput())
    
    def clean_username(self):
        """username must be unique  """
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError("username us already in use ")
        return username
    def clean(self):
        """verifique pass confirmation match"""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match')
        return data
    def save(self):
        """Create user and profile """
        data = self.cleaned_data
        data.pop('password_confirmation')   
        
        user = User.objects.create_user(**data) 
        profile = Profile(user=user)
        profile.save()

class ProfileForm(forms.ModelForm):
    website = forms.URLField(max_length=200,required=False)
    biography = forms.CharField(max_length=500,required=True)
    phone_number = forms.CharField(max_length=20,required=False)
    picture = forms.ImageField(required=True)

    class Meta:
        model = Profile
        fields = ['website', 'biography', 'phone_number', 'picture']

platzigram/users/views.py
"""Users views."""

# Django
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, DetailView,UpdateView

# Models
from django.contrib.auth.models import User
from posts.models import Post

# Forms
from users.models import Profile
from users.forms import ProfileForm ,SignUpForm


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

# def signup(request):
#     """Sign up view."""
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('users:login')
#     else:
#         form = SignupForm()

#     return render(
#         request=request,
#         template_name='users/signup.html',
#         context={'form': form}
#     )
    
class SignupView(FormView):
    """Users sigup view"""
    template_name = 'users/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('users:login')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
# @login_required
# def update_profile(request):
#     """Update a user's profile view."""
#     profile = request.user.profile

#     if request.method == 'POST':
#         form = ProfileForm(request.POST, request.FILES)
#         if form.is_valid():
#             data = form.cleaned_data

#             profile.website = data['website']
#             profile.phone_number = data['phone_number']
#             profile.biography = data['biography']
#             profile.picture = data['picture']
#             profile.save()

#             url = reverse('users:detail', kwargs={'username': request.user.username})
#             return redirect(url)

#     else:
#         form = ProfileForm()

#     return render(
#         request=request,
#         template_name='users/update_profile.html',
#         context={
#             'profile': profile,
#             'user': request.user,
#             'form': form
#         }
#     )


class UpdateProfileView(LoginRequiredMixin, UpdateView):
  """ Update profile view """

  model = Profile
  form_class = ProfileForm
  template_name = 'users/update_profile.html'
 

  def get_object(self, queryset=None):
    """ Return user's profile """
    return self.request.user.profile

  def get_success_url(self):
    """ Return to user's profile with a valid form """
    username = self.object.user.username
    return reverse_lazy('users:detail', kwargs={'username': username})


# def login_view(request):
#     """Login view."""
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user:
#             login(request, user)
#             return redirect('posts:feed')
#         else:
#             return render(request, 'users/login.html', {'error': 'Invalid username and password'})

#     return render(request, 'users/login.html')




@login_required
def logout_view(request):
    """Logout a user."""
    logout(request)
    return redirect('users:logout')

class LoginView(auth_views.LoginView):
    """Login View"""
    template_name= "users/login.html"

class LogoutView(LoginRequiredMixin,auth_views.LogoutView):
    template_name ='users/logout.html'

platzigram/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

platzigram/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded-circle"
                    width="150px"
                />
            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>

                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

platzigram/templates/users/login.html
{% extends 'users/base.html' %}

{% block head_content %}
<title>platzi sign in</title>
{% endblock  %}


{% block container  %}
{% if form.errors %}
<p class="alert alert-danger">Your username and password didn't match. plase try again </p>

{% endif %}
<form method="POST" action= "{% url "users:login" %}"> 
    {% csrf_token %}
    <div class = "form-group">
        <input  class="form-control" type="text" placeholder="Username" name="username" ></input>
    </div>
     <div class = "form-group">
        <input  class="form-control" type="password" placeholder="Password" name="password" ></input>
    </div>
    
    <button class="btn btn-primary btn-block mt-5" type="submit" >Sign  in</button>


</form>

<p class="mt-4">Dont have account yet? <a href="{% url "users:signup" %}" > sign up here</a> </p>

{% endblock  %}

platzigram/templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}



    <form action="{% url "users:signup" %}" method="POST">
        {% csrf_token %}

        {{form.as_p}}
      

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

platzigram/templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profiles</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4"id="profile-box">

            <form action="{% url 'users:update'%}" method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               
  
                
                <div class='media'>
                    
                    {% if profile.picture %}
                      <img src="{{profile.picture.url}}" class="rounded-circle"height="50"/>

                    {%else%}
                     <img src="{% static 'img/default-profile.png' %}"class="rounded-circle"height="50"/>
                    {% endif %}
                      
                    
                    
                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{user.get_full_name}}</h5>
                        <p class="ml-4"><input type="file"name="picture"required="true"></p>
                    </div>
                </div>
                {% for error in form.picture.errors  %}
                    <div class="alert alert-danger">
                        <b>Picture:</b>{{error}}
                    </div>
                 {% endfor %}


                <hr><br>
                   {#website field #}
                <div class="form-group">
                    <label>Website</label>
                    <input class="form-control {% if form.website.errors %}is-invalid{% endif %}"type="text"name="website"placeholder="Website"
                    value="{%if form.errors %}{{form.website.value}}{% else %}{{profile.website}}{%endif%}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors  %}
                          {{error}}
                        {% endfor %}

                    </div>
                </div>
             {#biography field #}
                <div class="form-group">
                    <label>Biography</label>
                    <textarea class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                    name="biography">
                    {%if form.errors %}{{form.biography.value}}{% else %}{{profile.biography}}{%endif%} 

                </textarea>
                <div class="invalid-feedback">
                    {% for error in form.biography.errors  %}
                      {{error}}
                    {% endfor %}

                </div>
                </div>
                {#phone number field #}
                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{%if form.errors %}{{form.phone_number.value}}{% else %}{{ profile.phone_number }}{%endif%} "
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors  %}
                          {{error}}
                        {% endfor %}
    
                    </div>
                </div>

                <button type="submit"class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}